allowBuilds:
  '@tailwindcss/oxide': true
  esbuild: true
  nx: true
  sharp: true
minimumReleaseAgeExclude:
  - '@builder.io/qwik-city@1.20.2'
  - '@builder.io/qwik@1.20.2'
  - eslint-plugin-qwik@1.20.2
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - nx
  - sharp
